(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_value
open OBus_value.C
open OBus_member
open OBus_object
module Org_foo_bar =
struct
  let interface = "org.foo.bar"
  let m_Ping = {
    Method.interface = interface;
    Method.member = "Ping";
    Method.i_args = (arg1
                       (None, basic_string));
    Method.o_args = (arg1
                       (None, basic_string));
    Method.annotations = [];
  }
  type 'a members = {
    m_Ping : 'a OBus_object.t -> string -> string Lwt.t;
  }
  let make members =
    OBus_object.make_interface_unsafe interface
      [
      ]
      [|
        method_info m_Ping members.m_Ping;
      |]
      [|
      |]
      [|
      |]
end
