(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member
module Org_foo_bar : sig
  val interface : OBus_name.interface
  val m_Ping : (string, string) Method.t
  type 'a members = {
    m_Ping : 'a OBus_object.t -> string -> string Lwt.t;
  }
  val make : 'a members -> 'a OBus_object.interface
end
